version: "3.8"

services:

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - PetsLostAndFoundSystem-network
    
    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks: 
            - PetsLostAndFoundSystem-network
            
    identity:
        container_name: identity
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Identity/Dockerfile
        ports: 
            - "5002:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data        
            
    reporters:
        container_name: reporters
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Reporters/Dockerfile
        ports: 
            - "5004:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundReportersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/reporters/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            
    statistics:
        container_name: statistics
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Statistics/Dockerfile
        ports: 
            - "5008:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundStatisticsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/statistics/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            
    publications:
        container_name: publications
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Publications/Dockerfile
        ports: 
            - "5006:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundPublicationsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
        restart: on-failure
        volumes:
            - ./.aspnet/mvc/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            
    mvc:
        container_name: mvc
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.MVC/Dockerfile
        ports: 
            - "5000:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        restart: on-failure
        volumes:
            - ./.aspnet/mvc/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            
    reportersgateway:
        container_name: reportersGateway
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Reporters.Gateway/Dockerfile
        ports: 
            - "5010:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        restart: on-failure
        volumes:
            - ./.aspnet/mvc/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            
    admin:
        container_name: admin
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Admin/Dockerfile
        ports: 
            - "5001:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        restart: on-failure
        volumes:
            - ./.aspnet/mvc/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            
    notifications:
        container_name: notifications
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Notifications/Dockerfile
        ports: 
            - "5012:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        restart: on-failure
        volumes:
            - ./.aspnet/mvc/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            
    watchdog:
        container_name: watchdog
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Watchdog/Dockerfile
        ports: 
            - "5014:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        restart: on-failure
        volumes:
            - ./.aspnet/mvc/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data

networks:
    PetsLostAndFoundSystem-network:

volumes:
    sqldata: