version: "3.8"

services:

    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports: 
            - "1433:1433"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes: 
            - sqldata:/var/opt/mssql 
        networks: 
            - PetsLostAndFoundSystem-network
    
    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: "rabbitmq"
        environment:
            - RABBITMQ_ERLANG_COOKIE=Rand0mR4bbitMqCo0k1e
            - RABBITMQ_DEFAULT_USER=rabbitmq
            - RABBITMQ_DEFAULT_PASS=rabbitmq
        networks: 
            - PetsLostAndFoundSystem-network
            
    identity:
        container_name: identity
        image: dimitvp/petslostandfoundsystem-identity-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Identity/Dockerfile
        ports: 
            - "5002:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundIdentityDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - IdentitySettings__AdminPassword=adminpass12!
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data        
            
    reporters:
        container_name: reporters
        image: dimitvp/petslostandfoundsystem-reporters-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Reporters/Dockerfile
        ports: 
            - "5004:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundReportersDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        volumes:
            - .data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            - messages
            
    statistics:
        container_name: statistics
        image: dimitvp/petslostandfoundsystem-statistics-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Statistics/Dockerfile
        ports: 
            - "5008:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundStatisticsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            - messages
            
    publications:
        container_name: publications
        image: dimitvp/petslostandfoundsystem-publications-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Publications/Dockerfile
        ports: 
            - "5006:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PetsLostAndFoundPublicationsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            - messages
            
    mvc:
        container_name: mvc
        image: dimitvp/petslostandfoundsystem-mvc-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.MVC/Dockerfile
        ports: 
            - "5000:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            - messages
            - identity
            - dealers
            - statistics
            - notifications
            
    reportersgateway:
        container_name: reportersGateway
        image: dimitvp/petslostandfoundsystem-reportersgateway-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Reporters.Gateway/Dockerfile
        ports: 
            - "5010:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - data
            - messages
            - identity
            - dealers
            - statistics
            - notifications
            
    admin:
        container_name: admin
        image: dimitvp/petslostandfoundsystem-admin-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Admin/Dockerfile
        ports: 
            - "5001:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - ServiceEndpoints__Identity=http://identity
            - ServiceEndpoints__Dealers=http://dealers
            - ServiceEndpoints__Statistics=http://statistics
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
             - identity
            - dealers
            - statistics
            
    notifications:
        container_name: notifications
        image: dimitvp/petslostandfoundsystem-notifications-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Notifications/Dockerfile
        ports: 
            - "5012:80"
        env_file: PetsLostAndFound/PetsLostAndFoundSystem/Common.env
        environment:
            - NotificationSettings__AllowedOrigins=http://localhost
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=rabbitmquser
            - MessageQueueSettings__Password=rabbitmqPassword12!
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - messages
            
    watchdog:
        container_name: watchdog
        image: dimitvp/petslostandfoundsystem-watchdog-services
        build:
            context: ./PetsLostAndFound
            dockerfile: ./PetsLostAndFoundSystem.Watchdog/Dockerfile
        ports: 
            - "5014:80"
         environment:
            - HealthChecks-UI__HealthChecks__0__Name=Identity
            - HealthChecks-UI__HealthChecks__0__Uri=http://identity/health
            - HealthChecks-UI__HealthChecks__1__Name=Dealers
            - HealthChecks-UI__HealthChecks__1__Uri=http://dealers/health
            - HealthChecks-UI__HealthChecks__2__Name=Statistics
            - HealthChecks-UI__HealthChecks__2__Uri=http://statistics/health
            - HealthChecks-UI__HealthChecks__3__Name=Notifications
            - HealthChecks-UI__HealthChecks__3__Uri=http://notifications/health
            - HealthChecks-UI__HealthChecks__4__Name=Admin
            - HealthChecks-UI__HealthChecks__4__Uri=http://admin/health
        restart: on-failure
        networks: 
            - PetsLostAndFoundSystem-network
        depends_on:
            - identity
            - dealers
            - statistics
            - notifications
            - admin

networks:
    PetsLostAndFoundSystem-network:

volumes:
    sqldata:
    rabbitmq:
    data-protection: